sudo: true

language: bash

services:
  - docker

script:
  - make docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: site
  fqdn: traggo.net
  on:
    branch: master
